### ISSUE TITLE
Publish osql as a package on popular package managers

### ISSUE THREAD

**Issue by mike-myers-tob** [osql/osql-experimental#6]
After `osql` is able to sign a package installer, which is a prerequisite to this, it should publish every "release" build to repos like `apt`, `yum`, `dnf`, `homebrew`, `Chocolatey`, etc.

**Comment by Smjert** [comment]
Would like to add that for yum repositories it's possible to sign the repository metadata, which describes its content/packages, to be sure that it has not been tampered with.
This is a procedure we likely have to take into account, also for the other type repositories.

**Comment by mike-myers-tob** [comment]
This is a job for upstream now.
